### ISSUE TITLE
Ens-squid-migration review

### ISSUE THREAD

**Issue by fortz007** [fortz007/Ens-squid-migration#1]
I was able to come up with the migration even though I am not a developer. Please consider
https://github.com/fortz007/Ens-squid-migration

**Comment by dariaag** [comment]
duplicate keys in batch upsert. try using map and inserting values from it instead of an array

<img width="1089" alt="Screenshot 2023-10-11 at 10 25 50" src="https://github.com/fortz007/Ens-squid-migration/assets/25107309/09318418-05d1-41ea-94ed-26d0af3646b7">

**Comment by fortz007** [comment]
> duplicate keys in batch upsert. try using map and inserting values from it instead of an array
> 
> <img alt="Screenshot 2023-10-11 at 10 25 50" width="1089" src="https://user-images.githubusercontent.com/25107309/274198358-09318418-05d1-41ea-94ed-26d0af3646b7.png">

Done and pushed. Please check

**Comment by dariaag** [comment]
1.database still throws an error. please run the squid locally before submitting and don't submit if it does not run
2. events are decoded but data from them is never saved
